# elasticsearch:
#   service:
#     type: NodePort
#     nodePort: 30001
#   minimumMasterNodes: 1
#   replicas: 1

# jaeger:
#   query:
#     service:
#       type: NodePort
#       nodePort: 30002
#   provisionDataStore:
#     cassandra: false
#   storage:
#     type: elasticsearch
#     elasticsearch:
#       host: elasticsearch-master
#       port: 9200


query:
  service:
    type: NodePort
    nodePort: 30002

elasticsearch:
  service:
    type: NodePort
    nodePort: 30001
  master:
    masterOnly: false
    replicaCount: 1
  data:
    replicaCount: 1
  coordinating:
    replicaCount: 0
  ingest:
    replicaCount: 1

provisionDataStore:
  cassandra: false
  elasticsearch: true

storage:
  type: elasticsearch
  elasticsearch:
    host: jaeger-elasticsearch-master-hl
    port: 9200


